baseURL = "https://peterampazzo.github.io/project-website-template/"
title = "Beer Data Analysis"
description = "Who is you beer drinker partner "
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Lucas Sylvester", "Lucas Emcken ", "Lila Meflah"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

