name = "Beer Data analysis"
license = "MIT"
description = ""
homepage = "https://github.com/lilameflah/Website-CSS-.git"
tags = []
features = []
min_version = "0.1.0"

[author]
  name = "Lucas Emcken, Lucas Sylvester, Lila Meflah"
  homepage = "github.com/lilameflah"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
